spring.application.name=loanservice

server.port=8082

#Loan API 
loan.api.base-url=https://demo9993930.mockable.io/loanaccount/


# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/loanaudit
spring.datasource.username=root
spring.datasource.password=root

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.com.assignment.loan=DEBUG