spring.application.name=loanservice

server.port=8082

#Loan API 
loan.api.base-url=https://demo9993930.mockable.io/loanaccount/

# Logging
logging.level.root=INFO
logging.level.com.assignment.loan=DEBUG